spring.application.name=AI-Integration
server.port=${PORT:9600}

gemini.api.key=${GEMINI_API_KEY}
groq.api.key=${GROQ_API_KEY}
openrouter.api.key=${OPENROUTER_API_KEY}
cohere.api.key=${COHERE_API_KEY}
mistral.api.key=${MISTRAL_API_KEY}